import { Listing } from './types';

export const fakeListings: Listing[] = [{
    id: '123',
    name: 'Old Boat',
    description: 'A very old boat. Bargain price',
    price: 700,
}, {
    id: '345',
    name: 'Computer',
    description: 'From the 1990s, a classic!',
    price: 50,
}, {
    id: '456',
    name: 'Basketball Hoop',
    description: 'Good condition, free delivery',
    price: 100,
}];

export const fakeMyListings: Listing[] = [{
    id: '789',
    name: 'Bicycle',
    description: 'Bright blue, very fast',
    price: 75,
}, {
    id: '234',
    name: 'Electric Guitar',
    description: 'Needs new strings, but otherwise in very good condition',
    price: 99,
}, {
    id: '987',
    name: 'Playstation',
    description: 'Old playstation, still works though',
    price: 75,
}];

export const contactList: any[] = [
    {
        "id": 1,
        "nombreCompleto": "J Loz Rojas",
        "telefonos": "626-7100,956749265",
        "email": "cbecerrag@pucp.pe,oquinto@gestorestecnologicos.com",
        "nombre": "Agencia Andina, 20.03.2019nombredelmedio",
        "activo": "1",
        "descripcion": null,
        "progamas_cargo": " : Director,NombreDeProgramaSuplemento : Productor/a,PRUEBA PROGRAMA : Productor/a",
        "activoContacto": 1,
        "mediosContacto": [
            {
                "id": 1,
                "nombre": "Agencia Andina",
                "alias": "AGENCIA ANDINA",
                "idCompanhia": 24,
                "pais": "Perú",
                "departamento": "Lima",
                "provincia": "Lima ",
                "distrito": "Lima",
                "ubigeo": "01150000",
                "direccion": "Av. Alfonso Ugarte 873, Lima",
                "referencia": "Frente al Hospital Arzobispo Loayza",
                "filial": "0",
                "idMedioPadre": null,
                "costo": null,
                "activo": 1,
                "descripcion": "Web de noticias de actualidad nacional e inte",
                "operadora": "Otros",
                "numeroTelefono": "3150400",
                "email": null,
                "web": "https://andina.pe/agencia/",
                "facebook": "https://www.facebook.com/agenciandina/",
                "twitter": "https://twitter.com/Agencia_andina",
                "instagram": null,
                "googlePlus": null,
                "pinterest": null,
                "periscope": null,
                "linkedin": "https://www.linkedin.com/company/agenciaandin",
                "blog": null,
                "created_at": null,
                "updated_at": "2020-05-28 12:13:04",
                "deleted_at": null
            },
            {
                "id": 182,
                "nombre": " 20.03.2019nombredelmedio",
                "alias": "20.03.2019Nombredelmedio",
                "idCompanhia": 1,
                "pais": "Perú",
                "departamento": "Amazonas",
                "provincia": "Chachapoyas",
                "distrito": "Chachapoyas",
                "ubigeo": "01150000",
                "direccion": "av mexico 365",
                "referencia": "referencia 1",
                "filial": "0",
                "idMedioPadre": 0,
                "costo": 0,
                "activo": 1,
                "descripcion": "descripcion",
                "operadora": "Bitel",
                "numeroTelefono": "985457458",
                "email": "email@pprios.com",
                "web": "",
                "facebook": "",
                "twitter": "",
                "instagram": "",
                "googlePlus": "",
                "pinterest": "",
                "periscope": "",
                "linkedin": "",
                "blog": "",
                "created_at": "2019-03-20 16:52:27",
                "updated_at": "2019-09-11 09:57:12",
                "deleted_at": null
            }
        ]
    },
    {
        "id": 2,
        "nombreCompleto": "Ernesto Carlín ",
        "telefonos": "999410521,3150400",
        "email": "ernestocarlin@gmail.com,ecarlin@editoraperu.com.pe",
        "nombre": "Agencia Andina,El Peruano",
        "activo": "1",
        "descripcion": "Cultura",
        "progamas_cargo": " : Periodista, : Redactor/a",
        "activoContacto": 1,
        "mediosContacto": [
            {
                "id": 1,
                "nombre": "Agencia Andina",
                "alias": "AGENCIA ANDINA",
                "idCompanhia": 24,
                "pais": "Perú",
                "departamento": "Lima",
                "provincia": "Lima ",
                "distrito": "Lima",
                "ubigeo": "01150000",
                "direccion": "Av. Alfonso Ugarte 873, Lima",
                "referencia": "Frente al Hospital Arzobispo Loayza",
                "filial": "0",
                "idMedioPadre": null,
                "costo": null,
                "activo": 1,
                "descripcion": "Web de noticias de actualidad nacional e inte",
                "operadora": "Otros",
                "numeroTelefono": "3150400",
                "email": null,
                "web": "https://andina.pe/agencia/",
                "facebook": "https://www.facebook.com/agenciandina/",
                "twitter": "https://twitter.com/Agencia_andina",
                "instagram": null,
                "googlePlus": null,
                "pinterest": null,
                "periscope": null,
                "linkedin": "https://www.linkedin.com/company/agenciaandin",
                "blog": null,
                "created_at": null,
                "updated_at": "2020-05-28 12:13:04",
                "deleted_at": null
            },
            {
                "id": 23,
                "nombre": "El Peruano",
                "alias": "EL PERUANO",
                "idCompanhia": 24,
                "pais": "Perú",
                "departamento": "Lima",
                "provincia": "Lima ",
                "distrito": "Lima",
                "ubigeo": "01150000",
                "direccion": "Av. Alfonso Ugarte 873",
                "referencia": null,
                "filial": "0",
                "idMedioPadre": null,
                "costo": null,
                "activo": 1,
                "descripcion": null,
                "operadora": null,
                "numeroTelefono": null,
                "email": null,
                "web": "http://www.elperuano.pe/",
                "facebook": "https://www.facebook.com/diariooficialelperua",
                "twitter": "https://twitter.com/DiarioElPeruano",
                "instagram": null,
                "googlePlus": null,
                "pinterest": null,
                "periscope": null,
                "linkedin": null,
                "blog": null,
                "created_at": null,
                "updated_at": "2020-07-13 12:23:32",
                "deleted_at": null
            }
        ]
    },
    {
        "id": 3,
        "nombreCompleto": "Clara Elvira Ospina ",
        "telefonos": "946212399",
        "email": "cospina@americatv.pe",
        "nombre": "Canal N, América TV",
        "activo": "1",
        "descripcion": null,
        "progamas_cargo": "Tiempo de leer : Conductor,Leer para Vivir : Director,De6a9 : Director,N Noticias : Director,N Directo : Director,Primero a las 12 : Director",
        "activoContacto": 1,
        "mediosContacto": [
            {
                "id": 8,
                "nombre": "Canal N",
                "alias": "CANAL N",
                "idCompanhia": 2,
                "pais": "Perú",
                "departamento": "Lima",
                "provincia": "Lima ",
                "distrito": "Lima",
                "ubigeo": "01150000",
                "direccion": "Montero Rosas 1099, Sta. Beatriz - Lima",
                "referencia": null,
                "filial": "0",
                "idMedioPadre": null,
                "costo": null,
                "activo": 1,
                "descripcion": "Canal 8 de Movistar TV",
                "operadora": null,
                "numeroTelefono": "4110808",
                "email": null,
                "web": "http://canaln.pe/",
                "facebook": "https://www.facebook.com/canal",
                "twitter": "https://twitter.com/canalN_",
                "instagram": null,
                "googlePlus": null,
                "pinterest": null,
                "periscope": null,
                "linkedin": null,
                "blog": null,
                "created_at": null,
                "updated_at": "2020-07-16 18:45:18",
                "deleted_at": null
            },
            {
                "id": 3,
                "nombre": " América TV",
                "alias": "AMÉRICA",
                "idCompanhia": 2,
                "pais": "Perú",
                "departamento": "Lima",
                "provincia": "Lima ",
                "distrito": "Lima",
                "ubigeo": "01150000",
                "direccion": "Jr. Montero Rosas 1099",
                "referencia": "Av. Cuba / Av. Alejandro Tirado",
                "filial": "0",
                "idMedioPadre": null,
                "costo": null,
                "activo": 1,
                "descripcion": null,
                "operadora": "Otros",
                "numeroTelefono": "4194000",
                "email": null,
                "web": null,
                "facebook": "https://www.facebook.com/americatelevision",
                "twitter": "https://twitter.com/americatv_peru",
                "instagram": null,
                "googlePlus": null,
                "pinterest": "https://www.pinterest.com/Americatvperu/",
                "periscope": null,
                "linkedin": null,
                "blog": null,
                "created_at": null,
                "updated_at": "2020-07-16 18:44:26",
                "deleted_at": null
            }
        ]
    }
];